be_simple_soap:
    services:
        TranscodingApi:
            namespace:     http://example.moritzwachter.de/wsdl/TranscodingApi/3.0/
            binding:       rpc-literal
            resource:      "@AppBundle/Controller/SOAP/TranscodingController.php"
            resource_type: annotation
        LivestreamApi:
            namespace:     http://example.moritzwachter.de/wsdl/LivestreamApi/3.0/
            binding:       rpc-literal
            resource:      "@AppBundle/Controller/SOAP/LivestreamController.php"
            resource_type: annotation