# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    fake.container:
        class: AppBundle\FakeContainer\FakeContainer
        arguments: ['@service_container']
