# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    fake.container:
        class: AppBundle\FakeContainer\FakeContainer
        arguments: ['@service_container']

    fake.service:
        class:   AppBundle\FakeContainer\FakeService

    soap.transcoding:
        class: AppBundle\SOAP\TranscodingSoapHandler
        arguments:
            - '@fake.service'
            - '@logger'
            - '@fake.service'
            - '@fake.service'

    soap.livestream:
        class: AppBundle\SOAP\LivestreamSoapHandler
        arguments:
            - '@fake.service'
            - '@logger'
            - '@fake.service'
            - '@fake.service'
            - '@fake.service'
